version: "2"
services:
  server-side:
    restart: always
    build: ./server-side
    ports:
      - "8000:8000"
    links:
      - mongo
  client-side:
    restart: always
    build: ./client-side
    ports:
      - "5000:5000"
    links:
      - server-side
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data
    ports:
      - "27017:27017"
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "8080:80"
    links:
      - server-side
      - client-side
